"""Generate LaTeX tables from ``analysis/output/summary.csv``.

The original MO-CAPO table script was hard-coded to four non-fairness datasets,
six optimizers, and a single 7.5M budget.  This version is dynamic and emits
separate 1M, 5M, and 7.5M tables for three-objective metrics and representative
quality/cost/fairness solutions.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Sequence

import numpy as np
import pandas as pd

from .config import (
    DATASET_LABELS,
    OPTIMIZER_LABELS,
    PRIMARY_BUDGETS,
    budget_label,
    parse_csv_ints,
)


MOO_METRICS = (
    ("hv_test_optimistic_3d", "HV$_{opt}$", "max"),
    ("hv_test_pessimistic_3d", "HV$_{pes}$", "max"),
    ("approximation_gap_3d", "Gap", "min"),
    ("noisy_r2_3d", "nR2", "min"),
)

BALANCED_METRICS = (
    ("balanced_test_quality", "Quality", "max"),
    ("balanced_test_cost", "Cost", "min"),
    ("balanced_test_fairness", "Unfairness", "min"),
    ("fairness_generalization_gap_abs", "$|\\Delta F|$", "min"),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--summary", default="analysis/output/summary.csv")
    parser.add_argument("--output-dir", default="analysis/output/tables")
    parser.add_argument(
        "--budgets", default=",".join(str(value) for value in PRIMARY_BUDGETS)
    )
    parser.add_argument("--decimals", type=int, default=3)
    return parser.parse_args()


def latex_escape(value: object) -> str:
    text = str(value)
    replacements = {
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
    }
    for source, target in replacements.items():
        text = text.replace(source, target)
    return text


def display_dataset(value: str) -> str:
    return DATASET_LABELS.get(str(value), str(value))


def display_optimizer(value: str) -> str:
    return OPTIMIZER_LABELS.get(str(value), str(value))


def is_best(value: float, values: pd.Series, direction: str) -> bool:
    finite = pd.to_numeric(values, errors="coerce").dropna()
    if not len(finite) or not np.isfinite(value):
        return False
    target = finite.max() if direction == "max" else finite.min()
    return bool(np.isclose(value, target, rtol=1e-9, atol=1e-12))


def format_mean_std(mean: float, std: float, *, bold: bool, decimals: int) -> str:
    if pd.isna(mean):
        return "---"
    mean_text = f"{float(mean):.{decimals}f}"
    std_text = "---" if pd.isna(std) else f"{float(std):.{decimals}f}"
    body = rf"{mean_text}_{{\pm {std_text}}}"
    return rf"$\mathbf{{{body}}}$" if bold else rf"${body}$"


def metric_cell(
    group: pd.DataFrame,
    row: pd.Series,
    metric: str,
    direction: str,
    decimals: int,
) -> str:
    mean_column = f"{metric}_mean"
    std_column = f"{metric}_std"
    if mean_column not in row:
        return "---"
    mean = float(row[mean_column]) if pd.notna(row[mean_column]) else float("nan")
    std = (
        float(row[std_column])
        if std_column in row and pd.notna(row[std_column])
        else float("nan")
    )
    return format_mean_std(
        mean,
        std,
        bold=is_best(mean, group[mean_column], direction),
        decimals=decimals,
    )


def make_budget_table(
    summary: pd.DataFrame,
    *,
    budget: int,
    metrics: Sequence[tuple[str, str, str]],
    caption: str,
    label: str,
    decimals: int,
) -> str:
    subset = summary[summary["budget_checkpoint"] == int(budget)].copy()
    if subset.empty:
        return f"% No rows available for budget {budget}\n"

    rows: list[str] = []
    for (dataset, model), group in subset.groupby(["dataset", "model"], sort=True):
        group = group.sort_values("optimizer")
        for row_number, (_, row) in enumerate(group.iterrows()):
            dataset_cell = (
                rf"\multirow{{{len(group)}}}{{*}}{{{latex_escape(display_dataset(dataset))}}}"
                if row_number == 0
                else ""
            )
            model_cell = latex_escape(model) if row_number == 0 else ""
            optimizer_cell = latex_escape(display_optimizer(row["optimizer"]))
            values = [
                metric_cell(group, row, metric, direction, decimals)
                for metric, _, direction in metrics
            ]
            rows.append(
                " & ".join([dataset_cell, model_cell, optimizer_cell, *values]) + r" \\"
            )
        rows.append(r"\midrule")
    if rows and rows[-1] == r"\midrule":
        rows.pop()

    metric_headers = " & ".join(rf"\textbf{{{header}}}" for _, header, _ in metrics)
    return rf"""% Auto-generated by analysis.make_paper_tables
\begin{{table*}}[t]
\centering
\caption{{{caption}}}
\label{{{label}}}
\small
\setlength{{\tabcolsep}}{{4pt}}
\begin{{tabular}}{{lll{"c" * len(metrics)}}}
\toprule
\textbf{{Dataset}} & \textbf{{Model}} & \textbf{{Optimizer}} & {metric_headers} \\
\midrule
{chr(10).join(rows)}
\\
\bottomrule
\end{{tabular}}
\end{{table*}}
"""


def make_budget_progression_table(
    summary: pd.DataFrame,
    *,
    budgets: Sequence[int],
    metric: str,
    direction: str,
    decimals: int,
) -> str:
    subset = summary[summary["budget_checkpoint"].isin(budgets)].copy()
    rows: list[str] = []
    for (dataset, model, optimizer), group in subset.groupby(
        ["dataset", "model", "optimizer"], sort=True
    ):
        cells = []
        for budget in budgets:
            row = group[group["budget_checkpoint"] == budget]
            if row.empty:
                cells.append("---")
                continue
            item = row.iloc[0]
            mean = item.get(f"{metric}_mean", np.nan)
            std = item.get(f"{metric}_std", np.nan)
            # Bolding is performed across methods at the same dataset/model/budget.
            comparison = subset[
                (subset["dataset"] == dataset)
                & (subset["model"] == model)
                & (subset["budget_checkpoint"] == budget)
            ]
            cells.append(
                format_mean_std(
                    float(mean),
                    float(std),
                    bold=is_best(float(mean), comparison[f"{metric}_mean"], direction),
                    decimals=decimals,
                )
            )
        rows.append(
            " & ".join(
                [
                    latex_escape(display_dataset(dataset)),
                    latex_escape(model),
                    latex_escape(display_optimizer(optimizer)),
                    *cells,
                ]
            )
            + r" \\"
        )

    headers = " & ".join(rf"\textbf{{{budget_label(value)}}}" for value in budgets)
    return rf"""% Auto-generated budget progression table
\begin{{table*}}[t]
\centering
\caption{{Pessimistic three-objective test hypervolume over the Tri-Fair budget ladder. Higher is better.}}
\label{{tab:tri_fair_budget_progression}}
\small
\begin{{tabular}}{{lll{"c" * len(budgets)}}}
\toprule
\textbf{{Dataset}} & \textbf{{Model}} & \textbf{{Optimizer}} & {headers} \\
\midrule
{chr(10).join(rows)}
\\
\bottomrule
\end{{tabular}}
\end{{table*}}
"""


def main() -> None:
    args = parse_args()
    summary = pd.read_csv(args.summary)
    budgets = parse_csv_ints(args.budgets)
    output = Path(args.output_dir)
    output.mkdir(parents=True, exist_ok=True)

    for budget in budgets:
        moo = make_budget_table(
            summary,
            budget=budget,
            metrics=MOO_METRICS,
            caption=(
                f"Three-objective Pareto-set results at a {budget_label(budget)} evaluation-token "
                "budget. Higher HV is better; lower approximation gap and nR2 are better. "
                "Values are mean $\\pm$ standard deviation over independent seeds."
            ),
            label=f"tab:tri_fair_moo_{budget}",
            decimals=args.decimals,
        )
        (output / f"moo_results_{budget}.tex").write_text(moo, encoding="utf-8")

        balanced = make_budget_table(
            summary,
            budget=budget,
            metrics=BALANCED_METRICS,
            caption=(
                f"Holdout performance of the balanced development-selected prompt at a "
                f"{budget_label(budget)} evaluation-token budget. Lower cost and unfairness are better."
            ),
            label=f"tab:tri_fair_balanced_{budget}",
            decimals=args.decimals,
        )
        (output / f"balanced_results_{budget}.tex").write_text(
            balanced, encoding="utf-8"
        )

    progression = make_budget_progression_table(
        summary,
        budgets=budgets,
        metric="hv_test_pessimistic_3d",
        direction="max",
        decimals=args.decimals,
    )
    (output / "budget_progression.tex").write_text(progression, encoding="utf-8")
    print(f"Wrote LaTeX tables to {output}")


if __name__ == "__main__":
    main()
